### ISSUE TITLE
batch[k] = torch.stack([f[k] for f in features])

### ISSUE THREAD

**Issue by HaithemH** [shahrukhx01/multitask-learning-transformers#1]
I tried to run the notebook https://colab.research.google.com/github/zphang/zphang.github.io/blob/master/files/notebooks/Multi_task_Training_with_Transformers_NLP.ipynb#scrollTo=U4YUxdIZz3_i
an error aquiered 
TypeError: expected Tensor as element 0 in argument 0, but got list.
It seems an type error in the NLPDataCollator class
batch[k] = torch.stack([f[k] for f in features])
in multitask_data_collator.py/, NLPDataCollator Class returns a batch as list.

**Comment by Nid989** [comment]
Hey, maybe there is some problem with the data coming from commonsenseQA data loaders since for each question there are multiple answers, you can resolve this by providing them in a batch as part of tensor, instead of supplying the same as a list.
Also in my case, I just replace the same with another dataset, and it worked fine.
Try using SQUADv2 instead.

**Comment by HaithemH** [comment]
Thank you for reacting
